### PR TITLE
Allow setting bottom bar background color

### PR DESCRIPTION
**Pull request by NBTX**
Added a 'color' parameter to the BubbleBottomBar widget:

Example usage -
```dart
          bottomNavigationBar: BubbleBottomBar(
            color: Colors.white,
            opacity: 0.2,
            currentIndex: pageIndex,
            onTap: (int index) => setState((){
              pageIndex = index;
            }),
            borderRadius: BorderRadius.vertical(top: Radius.circular(16)),
            elevation: 8,
            items: <BubbleBottomBarItem>[
              BubbleBottomBarItem(backgroundColor: Colors.red, icon: Icon(Icons.dashboard, color: Colors.black,), activeIcon: Icon(Icons.dashboard, color: Colors.red,), title: Text("Home")),
              BubbleBottomBarItem(backgroundColor: Colors.deepPurple, icon: Icon(Icons.access_time, color: Colors.black,), activeIcon: Icon(Icons.access_time, color: Colors.deepPurple,), title: Text("Logs")),
              BubbleBottomBarItem(backgroundColor: Colors.indigo, icon: Icon(Icons.folder_open, color: Colors.black,), activeIcon: Icon(Icons.folder_open, color: Colors.indigo,), title: Text("Folders")),
              BubbleBottomBarItem(backgroundColor: Colors.green, icon: Icon(Icons.menu, color: Colors.black,), activeIcon: Icon(Icons.menu, color: Colors.green,), title: Text("Menu"))
            ],
          ),
```

### CODE REVIEW

**Comment by westdabestdb** [comment]
Hello, this is a great addition, but can you please change color to backgroundColor? So this way it will be more understandable by new people to Flutter.

**Comment by NBTX** [comment]
Sure thing

**Comment by westdabestdb** [comment]
Thank you. Your change is now merged. Will publish on pub too.

**Comment by iampato** [comment]
What about a gradient ?

**Pull request merged**
